JDP230402-03 Added ProductDto, implemented basic endpoints for CartController
interceptor2048/project-jdp-2304-02 pull request #8
Opened 2023-04-03 10:58 UTC by JabAlex

2023-04-03 21:01 UTC, KamilBonar approved these changes

2023-04-04 14:24 UTC, mwojtyla commented
Hej, masz jakieś konflikty, nie wiem czy to nie przez to że dodajesz klasę ProductDto, którą już zrobił Witold, bo miał ją w swoim tasku.

2023-04-04 14:30 UTC, mwojtyla commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +public class ProductDto {
Nie powinna być raczej tabela CartDto?

2023-04-04 14:30 UTC, mwojtyla commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>  public class CartController {
Wydaje mi się że w kontrolerze powinny być odwołania do CartDto zamiast do ProductDto.

2023-04-04 14:30 UTC, mwojtyla commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +public class ProductDto {
W kontrolerze odwołujesz się nawet do cartId :)

2023-04-04 21:09 UTC, michal2220 requested changes

2023-04-04 21:09 UTC, michal2220 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        System.out.println("element " + productId + " removed from " + cartId);
Myślę, że fajnie by było jeszcze dodać opcję do usunięcia całego koszyka naraz, bez usuwania poszczególnych produktów z koszyka

2023-04-05 08:53 UTC, michal2220 approved these changes
Jak dla mnie jest ok, napisane zgodnie z ustaleniami :)

2023-04-05 08:53 UTC, michal2220 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void removeEverythingFromCart(@PathVariable Long cartId){
Ja tu bym jeszcze zmienił z removeEverythingFromCart na removeCart poprostu ale może się już czepiam :)

2023-04-05 15:21 UTC, merged

2023-04-07 18:57 UTC, WitoZak commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
Klasa wygląda inaczej, wiec nie wiem czy nie powinieneś na nią poczekać?

2023-04-07 18:57 UTC, WitoZak commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        System.out.println("Order created for cart " + cartId);
Wydaje mi się że nie jest to dobra praktyka by używać konsoli w http request-ach

2023-04-07 18:57 UTC, WitoZak commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
CartDto brak.

2023-04-07 18:57 UTC, WitoZak commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
Z-merg-uj się najpierw z origin/master i ta klasa nie będzie wtedy potrzebna w Twoim commicie

2023-04-07 18:57 UTC, WitoZak commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +public class ProductDto {
Nie chodzi o to byś poprawiał istniejące klasy tylko o to byś nie push-ował ich ponownie skoro już są w origin/master. Usuń tą klasę jak możesz i poprostu z-merg-uj branche